/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_change_monitor_changeMonitor_current_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()),
})
const _deepseek_ai_dsh_change_monitor_changeMonitor_current_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.union([z.literal(null), z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'turn': z.number().readonly(),
  'startedAt': z.number().readonly(),
  'finishedAt': z.number().readonly(),
  'root': z.string().readonly(),
  'files': z.array(z.object({
  'path': z.string().readonly(),
  'status': z.union([z.literal("added"), z.literal("deleted"), z.literal("modified")]).readonly(),
  'kind': z.union([z.literal("text"), z.literal("binary"), z.literal("large")]).readonly(),
  'additions': z.number().readonly(),
  'deletions': z.number().readonly(),
  'beforeSize': z.number().readonly(),
  'afterSize': z.number().readonly(),
  'summary': z.string().readonly().optional(),
})).readonly(),
  'additions': z.number().readonly(),
  'deletions': z.number().readonly(),
})]).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("internal"), z.literal("not-found"), z.literal("invalid-path")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_change_monitor_changeMonitor_debug_result$schema = z.object({
  'ok': z.literal(true),
  'value': z.array(z.object({
  'time': z.number(),
  'session': z.string(),
  'type': z.string(),
  'turn': z.number(),
})),
})
const _deepseek_ai_dsh_change_monitor_changeMonitor_file_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'turn': z.number().readonly(),
  'path': z.string().readonly(),
})
const _deepseek_ai_dsh_change_monitor_changeMonitor_file_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'path': z.string().readonly(),
  'status': z.union([z.literal("added"), z.literal("deleted"), z.literal("modified")]).readonly(),
  'kind': z.union([z.literal("text"), z.literal("binary"), z.literal("large")]).readonly(),
  'additions': z.number().readonly(),
  'deletions': z.number().readonly(),
  'beforeSize': z.number().readonly(),
  'afterSize': z.number().readonly(),
  'hunks': z.array(z.object({
  'oldStart': z.number().readonly(),
  'oldLines': z.number().readonly(),
  'newStart': z.number().readonly(),
  'newLines': z.number().readonly(),
  'lines': z.array(z.object({
  'kind': z.union([z.literal("context"), z.literal("add"), z.literal("del")]).readonly(),
  'oldLine': z.union([z.literal(null), z.number()]).readonly(),
  'newLine': z.union([z.literal(null), z.number()]).readonly(),
  'text': z.string().readonly(),
})).readonly(),
})).readonly(),
  'summary': z.string().readonly().optional(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("internal"), z.literal("not-found"), z.literal("invalid-path")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_change_monitor_changeMonitor_session_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_change_monitor_changeMonitor_session_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.union([z.literal(null), z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'turn': z.number().readonly(),
  'startedAt': z.number().readonly(),
  'finishedAt': z.number().readonly(),
  'root': z.string().readonly(),
  'files': z.array(z.object({
  'path': z.string().readonly(),
  'status': z.union([z.literal("added"), z.literal("deleted"), z.literal("modified")]).readonly(),
  'kind': z.union([z.literal("text"), z.literal("binary"), z.literal("large")]).readonly(),
  'additions': z.number().readonly(),
  'deletions': z.number().readonly(),
  'beforeSize': z.number().readonly(),
  'afterSize': z.number().readonly(),
  'summary': z.string().readonly().optional(),
})).readonly(),
  'additions': z.number().readonly(),
  'deletions': z.number().readonly(),
})]).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("internal"), z.literal("not-found"), z.literal("invalid-path")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_change_monitor_changeMonitor_turn_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'turn': z.number().readonly(),
})
const _deepseek_ai_dsh_change_monitor_changeMonitor_turn_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.union([z.literal(null), z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'turn': z.number().readonly(),
  'startedAt': z.number().readonly(),
  'finishedAt': z.number().readonly(),
  'root': z.string().readonly(),
  'files': z.array(z.object({
  'path': z.string().readonly(),
  'status': z.union([z.literal("added"), z.literal("deleted"), z.literal("modified")]).readonly(),
  'kind': z.union([z.literal("text"), z.literal("binary"), z.literal("large")]).readonly(),
  'additions': z.number().readonly(),
  'deletions': z.number().readonly(),
  'beforeSize': z.number().readonly(),
  'afterSize': z.number().readonly(),
  'summary': z.string().readonly().optional(),
})).readonly(),
  'additions': z.number().readonly(),
  'deletions': z.number().readonly(),
})]).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("internal"), z.literal("not-found"), z.literal("invalid-path")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
})])
const _deepseek_ai_dsh_change_monitor_changeMonitor_turns_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _deepseek_ai_dsh_change_monitor_changeMonitor_turns_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.array(z.object({
  'turn': z.number().readonly(),
  'startedAt': z.number().readonly(),
  'finishedAt': z.number().readonly(),
  'filesCount': z.number().readonly(),
  'additions': z.number().readonly(),
  'deletions': z.number().readonly(),
})).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.union([z.literal("internal"), z.literal("not-found"), z.literal("invalid-path")]).readonly(),
  'message': z.string().readonly(),
}).readonly(),
})])

export const TYPERT = {
  package: '@dsh-custom/dsh-change-monitor',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@dsh-custom/dsh-change-monitor#changeMonitor/current',
      service: 'changeMonitor',
      namespace: 'changeMonitor',
      method: 'current',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-custom/dsh-change-monitor#changeMonitor/current:request',
            schema: _deepseek_ai_dsh_change_monitor_changeMonitor_current_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-custom/dsh-change-monitor/types#ChangeSummaryResult',
        schema: _deepseek_ai_dsh_change_monitor_changeMonitor_current_result$schema,
      },
      sourceLocation: {"file":"packages/session/change-monitor/src/index.ts","line":456,"column":9},
    },
    {
      id: '@dsh-custom/dsh-change-monitor#changeMonitor/debug',
      service: 'changeMonitor',
      namespace: 'changeMonitor',
      method: 'debug',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-custom/dsh-change-monitor#changeMonitor/debug:result',
        schema: _deepseek_ai_dsh_change_monitor_changeMonitor_debug_result$schema,
      },
      sourceLocation: {"file":"packages/session/change-monitor/src/index.ts","line":470,"column":9},
    },
    {
      id: '@dsh-custom/dsh-change-monitor#changeMonitor/file',
      service: 'changeMonitor',
      namespace: 'changeMonitor',
      method: 'file',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-custom/dsh-change-monitor/types#ChangeFileRequest',
            schema: _deepseek_ai_dsh_change_monitor_changeMonitor_file_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-custom/dsh-change-monitor/types#ChangeFileResult',
        schema: _deepseek_ai_dsh_change_monitor_changeMonitor_file_result$schema,
      },
      sourceLocation: {"file":"packages/session/change-monitor/src/index.ts","line":494,"column":9},
    },
    {
      id: '@dsh-custom/dsh-change-monitor#changeMonitor/session',
      service: 'changeMonitor',
      namespace: 'changeMonitor',
      method: 'session',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-custom/dsh-change-monitor/types#ChangeSessionRequest',
            schema: _deepseek_ai_dsh_change_monitor_changeMonitor_session_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-custom/dsh-change-monitor/types#ChangeSummaryResult',
        schema: _deepseek_ai_dsh_change_monitor_changeMonitor_session_result$schema,
      },
      sourceLocation: {"file":"packages/session/change-monitor/src/index.ts","line":514,"column":9},
    },
    {
      id: '@dsh-custom/dsh-change-monitor#changeMonitor/turn',
      service: 'changeMonitor',
      namespace: 'changeMonitor',
      method: 'turn',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-custom/dsh-change-monitor/types#ChangeTurnRequest',
            schema: _deepseek_ai_dsh_change_monitor_changeMonitor_turn_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-custom/dsh-change-monitor/types#ChangeSummaryResult',
        schema: _deepseek_ai_dsh_change_monitor_changeMonitor_turn_result$schema,
      },
      sourceLocation: {"file":"packages/session/change-monitor/src/index.ts","line":480,"column":9},
    },
    {
      id: '@dsh-custom/dsh-change-monitor#changeMonitor/turns',
      service: 'changeMonitor',
      namespace: 'changeMonitor',
      method: 'turns',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-custom/dsh-change-monitor/types#ChangeTurnsRequest',
            schema: _deepseek_ai_dsh_change_monitor_changeMonitor_turns_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-custom/dsh-change-monitor/types#ChangeTurnsResult',
        schema: _deepseek_ai_dsh_change_monitor_changeMonitor_turns_result$schema,
      },
      sourceLocation: {"file":"packages/session/change-monitor/src/index.ts","line":443,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "The per-turn change monitor service. Listens to the durable session event stream — `turn/start` opens a before snapshot, `turn/end` settles, re-scans for stability, snapshots after, diffs, and stores. All of it runs inside contained best-effort wrappers.",
        "summary": "The per-turn change monitor service.",
        "tags": [],
        "jsDoc": "/**\n * The per-turn change monitor service. Listens to the durable session event\n * stream — `turn/start` opens a before snapshot, `turn/end` settles, re-scans\n * for stability, snapshots after, diffs, and stores. All of it runs inside\n * contained best-effort wrappers.\n */",
        "key": "changeMonitor",
        "exportName": "ChangeMonitorService",
        "members": [
          {
            "kind": "method",
            "name": "turns",
            "signature": "@Remote('turns') async turns(request: ChangeTurnsRequest): Promise<ChangeTurnsResult>",
            "summary": "`changeMonitor.turns`: completed turns, newest first.",
            "jsDoc": "/**\n * `changeMonitor.turns`: completed turns, newest first.\n * @param request - session whose history to read.\n * @returns turn summaries or a structured failure.\n */"
          },
          {
            "kind": "method",
            "name": "current",
            "signature": "@Remote('current') async current(request: { sessionId: SessionId }): Promise<ChangeSummaryResult>",
            "summary": "`changeMonitor.current`: the latest completed turn's summary.",
            "jsDoc": "/**\n * `changeMonitor.current`: the latest completed turn's summary.\n * @param request - session whose latest turn to read.\n * @returns the summary, or null when the session has no completed turn.\n */"
          },
          {
            "kind": "method",
            "name": "debug",
            "signature": "@Remote('debug') async debug(): Promise<{ ok: true; value: readonly { time: number; session: string; type: string; turn: number }[] }>",
            "summary": "`changeMonitor.debug`: recent session/event arrivals (diagnostic surface).",
            "jsDoc": "/**\n * `changeMonitor.debug`: recent session/event arrivals (diagnostic surface).\n * @returns the last received turn events with timestamps.\n */"
          },
          {
            "kind": "method",
            "name": "turn",
            "signature": "@Remote('turn') async turn(request: ChangeTurnRequest): Promise<ChangeSummaryResult>",
            "summary": "`changeMonitor.turn`: one exact completed turn's summary.",
            "jsDoc": "/**\n * `changeMonitor.turn`: one exact completed turn's summary.\n * @param request - session and turn number.\n * @returns the summary, or null when that turn has no record.\n */"
          },
          {
            "kind": "method",
            "name": "file",
            "signature": "@Remote('file') async file(request: ChangeFileRequest): Promise<ChangeFileResult>",
            "summary": "`changeMonitor.file`: one file's full diff inside one turn.",
            "jsDoc": "/**\n * `changeMonitor.file`: one file's full diff inside one turn. The path must\n * be a safe workspace-relative path; anything else is `invalid-path`.\n * @param request - session, turn, and workspace-relative path.\n * @returns the file's complete change record with hunks.\n */"
          },
          {
            "kind": "method",
            "name": "session",
            "signature": "@Remote('session') async session(request: ChangeSessionRequest): Promise<ChangeSummaryResult>",
            "summary": "`changeMonitor.session`: cumulative changes across every retained turn.",
            "jsDoc": "/**\n * `changeMonitor.session`: cumulative changes across every retained turn.\n * @param request - session whose cumulative changes to read.\n * @returns the merged summary, or null when nothing changed net.\n */"
          }
        ],
        "types": [
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "ChangeError",
            "declaration": "export interface ChangeError {\n    readonly code: ChangeMonitorErrorCode;\n    readonly message: string;\n}"
          },
          {
            "name": "ChangeFileKind",
            "declaration": "export type ChangeFileKind = 'text' | 'binary' | 'large';"
          },
          {
            "name": "ChangeFileRequest",
            "declaration": "export interface ChangeFileRequest {\n    readonly sessionId: SessionId;\n    readonly turn: number;\n    readonly path: string;\n}"
          },
          {
            "name": "ChangeFileResult",
            "declaration": "export type ChangeFileResult = { readonly ok: true; readonly value: FileChange; } | { readonly ok: false; readonly error: ChangeError; };"
          },
          {
            "name": "ChangeHunk",
            "declaration": "export interface ChangeHunk {\n    readonly oldStart: number;\n    readonly oldLines: number;\n    readonly newStart: number;\n    readonly newLines: number;\n    readonly lines: readonly ChangeLine[];\n}"
          },
          {
            "name": "ChangeLine",
            "declaration": "export interface ChangeLine {\n    readonly kind: 'context' | 'add' | 'del';\n    readonly oldLine: number | null;\n    readonly newLine: number | null;\n    readonly text: string;\n}"
          },
          {
            "name": "ChangeMonitorErrorCode",
            "declaration": "export type ChangeMonitorErrorCode = 'internal' | 'not-found' | 'invalid-path';"
          },
          {
            "name": "ChangeSessionRequest",
            "declaration": "export interface ChangeSessionRequest {\n    readonly sessionId: SessionId;\n}"
          },
          {
            "name": "ChangeSetSummary",
            "declaration": "export interface ChangeSetSummary {\n    readonly sessionId: SessionId;\n    readonly turn: number;\n    readonly startedAt: number;\n    readonly finishedAt: number;\n    readonly root: string;\n    readonly files: readonly FileChangeSummary[];\n    readonly additions: number;\n    readonly deletions: number;\n}"
          },
          {
            "name": "ChangeStatus",
            "declaration": "export type ChangeStatus = 'added' | 'deleted' | 'modified';"
          },
          {
            "name": "ChangeSummaryResult",
            "declaration": "export type ChangeSummaryResult = { readonly ok: true; readonly value: ChangeSetSummary | null; } | { readonly ok: false; readonly error: ChangeError; };"
          },
          {
            "name": "ChangeTurnRequest",
            "declaration": "export interface ChangeTurnRequest {\n    readonly sessionId: SessionId;\n    readonly turn: number;\n}"
          },
          {
            "name": "ChangeTurnsRequest",
            "declaration": "export interface ChangeTurnsRequest {\n    readonly sessionId: SessionId;\n}"
          },
          {
            "name": "ChangeTurnsResult",
            "declaration": "export type ChangeTurnsResult = { readonly ok: true; readonly value: readonly TurnSummary[]; } | { readonly ok: false; readonly error: ChangeError; };"
          },
          {
            "name": "FileChange",
            "declaration": "export interface FileChange {\n    readonly path: string;\n    readonly status: ChangeStatus;\n    readonly kind: ChangeFileKind;\n    readonly additions: number;\n    readonly deletions: number;\n    readonly beforeSize: number;\n    readonly afterSize: number;\n    readonly hunks: readonly ChangeHunk[];\n    readonly summary?: string;\n}"
          },
          {
            "name": "FileChangeSummary",
            "declaration": "export interface FileChangeSummary {\n    readonly path: string;\n    readonly status: ChangeStatus;\n    readonly kind: ChangeFileKind;\n    readonly additions: number;\n    readonly deletions: number;\n    readonly beforeSize: number;\n    readonly afterSize: number;\n    readonly summary?: string;\n}"
          },
          {
            "name": "SessionId",
            "declaration": "export type SessionId = Branded<'SessionId'>;"
          },
          {
            "name": "TurnSummary",
            "declaration": "export interface TurnSummary {\n    readonly turn: number;\n    readonly startedAt: number;\n    readonly finishedAt: number;\n    readonly filesCount: number;\n    readonly additions: number;\n    readonly deletions: number;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
