/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { ChangeFileRequest, ChangeFileResult, ChangeSessionRequest, ChangeSummaryResult, ChangeTurnRequest, ChangeTurnsRequest, ChangeTurnsResult } from '@dsh-custom/dsh-change-monitor/types'
import type { SessionId } from '@deepseek-ai/dsh-session/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6368616e67654d6f6e69746f72 {
    current: (request: { sessionId: SessionId; }) => Promise<RemoteResult<ChangeSummaryResult>>
    debug: () => Promise<RemoteResult<{ ok: true; value: readonly { time: number; session: string; type: string; turn: number; }[]; }>>
    file: (request: ChangeFileRequest) => Promise<RemoteResult<ChangeFileResult>>
    session: (request: ChangeSessionRequest) => Promise<RemoteResult<ChangeSummaryResult>>
    turn: (request: ChangeTurnRequest) => Promise<RemoteResult<ChangeSummaryResult>>
    turns: (request: ChangeTurnsRequest) => Promise<RemoteResult<ChangeTurnsResult>>
  }
  interface TypertRemoteMap {
    'changeMonitor/current': (request: { sessionId: SessionId; }) => Promise<RemoteResult<ChangeSummaryResult>>
    'changeMonitor/debug': () => Promise<RemoteResult<{ ok: true; value: readonly { time: number; session: string; type: string; turn: number; }[]; }>>
    'changeMonitor/file': (request: ChangeFileRequest) => Promise<RemoteResult<ChangeFileResult>>
    'changeMonitor/session': (request: ChangeSessionRequest) => Promise<RemoteResult<ChangeSummaryResult>>
    'changeMonitor/turn': (request: ChangeTurnRequest) => Promise<RemoteResult<ChangeSummaryResult>>
    'changeMonitor/turns': (request: ChangeTurnsRequest) => Promise<RemoteResult<ChangeTurnsResult>>
  }
  interface TypertRemoteNamespaceMap {
    'changeMonitor': TypertRemoteNamespace$6368616e67654d6f6e69746f72
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
