/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { GitRemoteBranchListView, GitRemoteCheckpointListRequest, GitRemoteCheckpointListView, GitRemoteCheckpointRestoreRequest, GitRemoteCommitRequest, GitRemoteCommitView, GitRemoteDiffRequest, GitRemoteDiffView, GitRemoteGeneratedMessageView, GitRemoteLogRequest, GitRemoteLogView, GitRemotePushRequest, GitRemotePushView, GitRemoteResult, GitRemoteSessionRequest, GitRemoteStageRequest, GitRemoteStageView, GitRemoteStatusView } from '@dsh-custom/dsh-git-remote/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$67697452656d6f7465 {
    branches: (request: GitRemoteSessionRequest) => Promise<RemoteResult<GitRemoteResult<GitRemoteBranchListView>>>
    checkpoints: (request: GitRemoteCheckpointListRequest) => Promise<RemoteResult<GitRemoteResult<GitRemoteCheckpointListView>>>
    commit: (request: GitRemoteCommitRequest) => Promise<RemoteResult<GitRemoteResult<GitRemoteCommitView>>>
    diff: (request: GitRemoteDiffRequest) => Promise<RemoteResult<GitRemoteResult<GitRemoteDiffView>>>
    generateCommitMessage: (request: GitRemoteSessionRequest) => Promise<RemoteResult<GitRemoteResult<GitRemoteGeneratedMessageView>>>
    log: (request: GitRemoteLogRequest) => Promise<RemoteResult<GitRemoteResult<GitRemoteLogView>>>
    push: (request: GitRemotePushRequest) => Promise<RemoteResult<GitRemoteResult<GitRemotePushView>>>
    restoreCheckpoint: (request: GitRemoteCheckpointRestoreRequest) => Promise<RemoteResult<GitRemoteResult<{ restored: readonly string[]; }>>>
    stage: (request: GitRemoteStageRequest) => Promise<RemoteResult<GitRemoteResult<GitRemoteStageView>>>
    status: (request: GitRemoteSessionRequest) => Promise<RemoteResult<GitRemoteResult<GitRemoteStatusView>>>
    unstage: (request: GitRemoteStageRequest) => Promise<RemoteResult<GitRemoteResult<GitRemoteStageView>>>
  }
  interface TypertRemoteMap {
    'gitRemote/branches': (request: GitRemoteSessionRequest) => Promise<RemoteResult<GitRemoteResult<GitRemoteBranchListView>>>
    'gitRemote/checkpoints': (request: GitRemoteCheckpointListRequest) => Promise<RemoteResult<GitRemoteResult<GitRemoteCheckpointListView>>>
    'gitRemote/commit': (request: GitRemoteCommitRequest) => Promise<RemoteResult<GitRemoteResult<GitRemoteCommitView>>>
    'gitRemote/diff': (request: GitRemoteDiffRequest) => Promise<RemoteResult<GitRemoteResult<GitRemoteDiffView>>>
    'gitRemote/generateCommitMessage': (request: GitRemoteSessionRequest) => Promise<RemoteResult<GitRemoteResult<GitRemoteGeneratedMessageView>>>
    'gitRemote/log': (request: GitRemoteLogRequest) => Promise<RemoteResult<GitRemoteResult<GitRemoteLogView>>>
    'gitRemote/push': (request: GitRemotePushRequest) => Promise<RemoteResult<GitRemoteResult<GitRemotePushView>>>
    'gitRemote/restoreCheckpoint': (request: GitRemoteCheckpointRestoreRequest) => Promise<RemoteResult<GitRemoteResult<{ restored: readonly string[]; }>>>
    'gitRemote/stage': (request: GitRemoteStageRequest) => Promise<RemoteResult<GitRemoteResult<GitRemoteStageView>>>
    'gitRemote/status': (request: GitRemoteSessionRequest) => Promise<RemoteResult<GitRemoteResult<GitRemoteStatusView>>>
    'gitRemote/unstage': (request: GitRemoteStageRequest) => Promise<RemoteResult<GitRemoteResult<GitRemoteStageView>>>
  }
  interface TypertRemoteNamespaceMap {
    'gitRemote': TypertRemoteNamespace$67697452656d6f7465
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
