/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _dsh_custom_dsh_git_remote_gitRemote_branches_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _dsh_custom_dsh_git_remote_gitRemote_branches_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.string().readonly(),
  'denied': z.boolean().readonly().optional(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'branches': z.array(z.object({
  'name': z.string().readonly(),
  'current': z.boolean().readonly(),
  'shortHash': z.string().readonly(),
  'upstream': z.string().readonly().optional(),
})).readonly(),
}).readonly(),
})])
const _dsh_custom_dsh_git_remote_gitRemote_checkpoints_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _dsh_custom_dsh_git_remote_gitRemote_checkpoints_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.string().readonly(),
  'denied': z.boolean().readonly().optional(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'checkpoints': z.array(z.object({
  'series': z.string().readonly(),
  'index': z.number().readonly(),
  'hash': z.string().readonly(),
  'shortHash': z.string().readonly(),
  'label': z.string().readonly(),
  'date': z.string().readonly(),
})).readonly(),
}).readonly(),
})])
const _dsh_custom_dsh_git_remote_gitRemote_commit_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'message': z.string().readonly(),
})
const _dsh_custom_dsh_git_remote_gitRemote_commit_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.string().readonly(),
  'denied': z.boolean().readonly().optional(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'hash': z.string().readonly(),
  'shortHash': z.string().readonly(),
  'subject': z.string().readonly(),
}).readonly(),
})])
const _dsh_custom_dsh_git_remote_gitRemote_diff_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'staged': z.boolean().readonly().optional(),
  'path': z.string().readonly().optional(),
})
const _dsh_custom_dsh_git_remote_gitRemote_diff_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.string().readonly(),
  'denied': z.boolean().readonly().optional(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'staged': z.boolean().readonly(),
  'patch': z.string().readonly(),
  'truncated': z.boolean().readonly(),
  'path': z.string().readonly().optional(),
}).readonly(),
})])
const _dsh_custom_dsh_git_remote_gitRemote_generateCommitMessage_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _dsh_custom_dsh_git_remote_gitRemote_generateCommitMessage_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.string().readonly(),
  'denied': z.boolean().readonly().optional(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'message': z.string().readonly(),
}).readonly(),
})])
const _dsh_custom_dsh_git_remote_gitRemote_log_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'maxCount': z.number().readonly().optional(),
  'ref': z.string().readonly().optional(),
  'path': z.string().readonly().optional(),
})
const _dsh_custom_dsh_git_remote_gitRemote_log_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.string().readonly(),
  'denied': z.boolean().readonly().optional(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'entries': z.array(z.object({
  'hash': z.string().readonly(),
  'shortHash': z.string().readonly(),
  'author': z.string().readonly(),
  'date': z.string().readonly(),
  'subject': z.string().readonly(),
})).readonly(),
}).readonly(),
})])
const _dsh_custom_dsh_git_remote_gitRemote_push_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'remote': z.string().readonly().optional(),
  'branch': z.string().readonly().optional(),
  'setUpstream': z.boolean().readonly().optional(),
})
const _dsh_custom_dsh_git_remote_gitRemote_push_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.string().readonly(),
  'denied': z.boolean().readonly().optional(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'remote': z.string().readonly(),
  'branch': z.string().readonly(),
  'setUpstream': z.boolean().readonly(),
}).readonly(),
})])
const _dsh_custom_dsh_git_remote_gitRemote_restoreCheckpoint_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'index': z.number().readonly(),
  'paths': z.array(z.string()).readonly().optional(),
})
const _dsh_custom_dsh_git_remote_gitRemote_restoreCheckpoint_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.string().readonly(),
  'denied': z.boolean().readonly().optional(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'restored': z.array(z.string()),
}).readonly(),
})])
const _dsh_custom_dsh_git_remote_gitRemote_stage_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'paths': z.array(z.string()).readonly().optional(),
  'all': z.boolean().readonly().optional(),
})
const _dsh_custom_dsh_git_remote_gitRemote_stage_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.string().readonly(),
  'denied': z.boolean().readonly().optional(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'stagedPaths': z.array(z.string()).readonly(),
}).readonly(),
})])
const _dsh_custom_dsh_git_remote_gitRemote_status_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const _dsh_custom_dsh_git_remote_gitRemote_status_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.string().readonly(),
  'denied': z.boolean().readonly().optional(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'root': z.string().readonly(),
  'ahead': z.number().readonly(),
  'behind': z.number().readonly(),
  'initial': z.boolean().readonly(),
  'detached': z.boolean().readonly(),
  'branch': z.string().readonly().optional(),
  'upstream': z.string().readonly().optional(),
  'entries': z.array(z.object({
  'code': z.string().readonly(),
  'path': z.string().readonly(),
  'staged': z.boolean().readonly(),
  'unstaged': z.boolean().readonly(),
  'untracked': z.boolean().readonly(),
  'originPath': z.string().readonly().optional(),
})).readonly(),
}).readonly(),
})])
const _dsh_custom_dsh_git_remote_gitRemote_unstage_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'paths': z.array(z.string()).readonly().optional(),
  'all': z.boolean().readonly().optional(),
})
const _dsh_custom_dsh_git_remote_gitRemote_unstage_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.string().readonly(),
  'denied': z.boolean().readonly().optional(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'stagedPaths': z.array(z.string()).readonly(),
}).readonly(),
})])

export const TYPERT = {
  package: '@dsh-custom/dsh-git-remote',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@dsh-custom/dsh-git-remote#gitRemote/branches',
      service: 'gitRemote',
      namespace: 'gitRemote',
      method: 'branches',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-custom/dsh-git-remote/types#GitRemoteSessionRequest',
            schema: _dsh_custom_dsh_git_remote_gitRemote_branches_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-custom/dsh-git-remote/types#GitRemoteResult',
        schema: _dsh_custom_dsh_git_remote_gitRemote_branches_result$schema,
      },
      sourceLocation: {"file":"packages/git/git-remote/src/index.ts","line":281,"column":9},
    },
    {
      id: '@dsh-custom/dsh-git-remote#gitRemote/checkpoints',
      service: 'gitRemote',
      namespace: 'gitRemote',
      method: 'checkpoints',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-custom/dsh-git-remote/types#GitRemoteCheckpointListRequest',
            schema: _dsh_custom_dsh_git_remote_gitRemote_checkpoints_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-custom/dsh-git-remote/types#GitRemoteResult',
        schema: _dsh_custom_dsh_git_remote_gitRemote_checkpoints_result$schema,
      },
      sourceLocation: {"file":"packages/git/git-remote/src/index.ts","line":420,"column":9},
    },
    {
      id: '@dsh-custom/dsh-git-remote#gitRemote/commit',
      service: 'gitRemote',
      namespace: 'gitRemote',
      method: 'commit',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-custom/dsh-git-remote/types#GitRemoteCommitRequest',
            schema: _dsh_custom_dsh_git_remote_gitRemote_commit_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-custom/dsh-git-remote/types#GitRemoteResult',
        schema: _dsh_custom_dsh_git_remote_gitRemote_commit_result$schema,
      },
      sourceLocation: {"file":"packages/git/git-remote/src/index.ts","line":326,"column":9},
    },
    {
      id: '@dsh-custom/dsh-git-remote#gitRemote/diff',
      service: 'gitRemote',
      namespace: 'gitRemote',
      method: 'diff',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-custom/dsh-git-remote/types#GitRemoteDiffRequest',
            schema: _dsh_custom_dsh_git_remote_gitRemote_diff_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-custom/dsh-git-remote/types#GitRemoteResult',
        schema: _dsh_custom_dsh_git_remote_gitRemote_diff_result$schema,
      },
      sourceLocation: {"file":"packages/git/git-remote/src/index.ts","line":248,"column":9},
    },
    {
      id: '@dsh-custom/dsh-git-remote#gitRemote/generateCommitMessage',
      service: 'gitRemote',
      namespace: 'gitRemote',
      method: 'generateCommitMessage',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-custom/dsh-git-remote/types#GitRemoteSessionRequest',
            schema: _dsh_custom_dsh_git_remote_gitRemote_generateCommitMessage_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-custom/dsh-git-remote/types#GitRemoteResult',
        schema: _dsh_custom_dsh_git_remote_gitRemote_generateCommitMessage_result$schema,
      },
      sourceLocation: {"file":"packages/git/git-remote/src/index.ts","line":365,"column":9},
    },
    {
      id: '@dsh-custom/dsh-git-remote#gitRemote/log',
      service: 'gitRemote',
      namespace: 'gitRemote',
      method: 'log',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-custom/dsh-git-remote/types#GitRemoteLogRequest',
            schema: _dsh_custom_dsh_git_remote_gitRemote_log_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-custom/dsh-git-remote/types#GitRemoteResult',
        schema: _dsh_custom_dsh_git_remote_gitRemote_log_result$schema,
      },
      sourceLocation: {"file":"packages/git/git-remote/src/index.ts","line":264,"column":9},
    },
    {
      id: '@dsh-custom/dsh-git-remote#gitRemote/push',
      service: 'gitRemote',
      namespace: 'gitRemote',
      method: 'push',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-custom/dsh-git-remote/types#GitRemotePushRequest',
            schema: _dsh_custom_dsh_git_remote_gitRemote_push_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-custom/dsh-git-remote/types#GitRemoteResult',
        schema: _dsh_custom_dsh_git_remote_gitRemote_push_result$schema,
      },
      sourceLocation: {"file":"packages/git/git-remote/src/index.ts","line":342,"column":9},
    },
    {
      id: '@dsh-custom/dsh-git-remote#gitRemote/restoreCheckpoint',
      service: 'gitRemote',
      namespace: 'gitRemote',
      method: 'restoreCheckpoint',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-custom/dsh-git-remote/types#GitRemoteCheckpointRestoreRequest',
            schema: _dsh_custom_dsh_git_remote_gitRemote_restoreCheckpoint_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-custom/dsh-git-remote/types#GitRemoteResult',
        schema: _dsh_custom_dsh_git_remote_gitRemote_restoreCheckpoint_result$schema,
      },
      sourceLocation: {"file":"packages/git/git-remote/src/index.ts","line":438,"column":9},
    },
    {
      id: '@dsh-custom/dsh-git-remote#gitRemote/stage',
      service: 'gitRemote',
      namespace: 'gitRemote',
      method: 'stage',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-custom/dsh-git-remote/types#GitRemoteStageRequest',
            schema: _dsh_custom_dsh_git_remote_gitRemote_stage_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-custom/dsh-git-remote/types#GitRemoteResult',
        schema: _dsh_custom_dsh_git_remote_gitRemote_stage_result$schema,
      },
      sourceLocation: {"file":"packages/git/git-remote/src/index.ts","line":294,"column":9},
    },
    {
      id: '@dsh-custom/dsh-git-remote#gitRemote/status',
      service: 'gitRemote',
      namespace: 'gitRemote',
      method: 'status',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-custom/dsh-git-remote/types#GitRemoteSessionRequest',
            schema: _dsh_custom_dsh_git_remote_gitRemote_status_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-custom/dsh-git-remote/types#GitRemoteResult',
        schema: _dsh_custom_dsh_git_remote_gitRemote_status_result$schema,
      },
      sourceLocation: {"file":"packages/git/git-remote/src/index.ts","line":235,"column":9},
    },
    {
      id: '@dsh-custom/dsh-git-remote#gitRemote/unstage',
      service: 'gitRemote',
      namespace: 'gitRemote',
      method: 'unstage',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-custom/dsh-git-remote/types#GitRemoteStageRequest',
            schema: _dsh_custom_dsh_git_remote_gitRemote_unstage_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-custom/dsh-git-remote/types#GitRemoteResult',
        schema: _dsh_custom_dsh_git_remote_gitRemote_unstage_result$schema,
      },
      sourceLocation: {"file":"packages/git/git-remote/src/index.ts","line":310,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "tags": [],
        "key": "gitRemote",
        "exportName": "GitRemoteService",
        "members": [
          {
            "kind": "method",
            "name": "status",
            "signature": "@Remote('status') async status(request: GitRemoteSessionRequest): Promise<GitRemoteResult<GitRemoteStatusView>>",
            "summary": "`gitRemote.status`: the session repository's working-tree status.",
            "jsDoc": "/**\n * `gitRemote.status`: the session repository's working-tree status.\n * @param request - the session whose repository to read.\n * @returns the status view, or the failure the panel renders.\n */"
          },
          {
            "kind": "method",
            "name": "diff",
            "signature": "@Remote('diff') async diff(request: GitRemoteDiffRequest): Promise<GitRemoteResult<GitRemoteDiffView>>",
            "summary": "`gitRemote.diff`: one unified diff of the session repository.",
            "jsDoc": "/**\n * `gitRemote.diff`: one unified diff of the session repository.\n * @param request - the session, staged/work-tree selection, and optional path filter.\n * @returns the patch view, or the failure the panel renders.\n */"
          },
          {
            "kind": "method",
            "name": "log",
            "signature": "@Remote('log') async log(request: GitRemoteLogRequest): Promise<GitRemoteResult<GitRemoteLogView>>",
            "summary": "`gitRemote.log`: the session repository's commit list.",
            "jsDoc": "/**\n * `gitRemote.log`: the session repository's commit list.\n * @param request - the session, count bound, optional revision and path filter.\n * @returns the commit list view, or the failure the panel renders.\n */"
          },
          {
            "kind": "method",
            "name": "branches",
            "signature": "@Remote('branches') async branches(request: GitRemoteSessionRequest): Promise<GitRemoteResult<GitRemoteBranchListView>>",
            "summary": "`gitRemote.branches`: the session repository's local branches.",
            "jsDoc": "/**\n * `gitRemote.branches`: the session repository's local branches.\n * @param request - the session whose repository to read.\n * @returns the branch list view, or the failure the panel renders.\n */"
          },
          {
            "kind": "method",
            "name": "stage",
            "signature": "@Remote('stage') async stage(request: GitRemoteStageRequest): Promise<GitRemoteResult<GitRemoteStageView>>",
            "summary": "`gitRemote.stage`: stage work-tree changes into the index.",
            "jsDoc": "/**\n * `gitRemote.stage`: stage work-tree changes into the index.\n * @param request - the session and the paths (or the whole work tree).\n * @returns the cumulative staged paths, or the failure the panel renders.\n */"
          },
          {
            "kind": "method",
            "name": "unstage",
            "signature": "@Remote('unstage') async unstage(request: GitRemoteStageRequest): Promise<GitRemoteResult<GitRemoteStageView>>",
            "summary": "`gitRemote.unstage`: return index entries to HEAD.",
            "jsDoc": "/**\n * `gitRemote.unstage`: return index entries to HEAD.\n * @param request - the session and the paths (or the whole index).\n * @returns the cumulative staged paths, or the failure the panel renders.\n */"
          },
          {
            "kind": "method",
            "name": "commit",
            "signature": "@Remote('commit') async commit(request: GitRemoteCommitRequest): Promise<GitRemoteResult<GitRemoteCommitView>>",
            "summary": "`gitRemote.commit`: create one commit from the staged index.",
            "jsDoc": "/**\n * `gitRemote.commit`: create one commit from the staged index.\n * @param request - the session and the commit message.\n * @returns the created commit's identity, or the failure the panel renders.\n */"
          },
          {
            "kind": "method",
            "name": "push",
            "signature": "@Remote('push') async push(request: GitRemotePushRequest): Promise<GitRemoteResult<GitRemotePushView>>",
            "summary": "`gitRemote.push`: push the current branch to its upstream or an explicit remote.",
            "jsDoc": "/**\n * `gitRemote.push`: push the current branch to its upstream or an explicit remote.\n * @param request - the session, optional remote/branch, and upstream setup.\n * @returns the push target echo, or the failure the panel renders.\n */"
          },
          {
            "kind": "method",
            "name": "generateCommitMessage",
            "signature": "@Remote('generateCommitMessage') async generateCommitMessage(request: GitRemoteSessionRequest): Promise<GitRemoteResult<GitRemoteGeneratedMessageView>>",
            "summary": "`gitRemote.generateCommitMessage`: one auxiliary model completion that drafts the commit message from the staged diff.",
            "jsDoc": "/**\n * `gitRemote.generateCommitMessage`: one auxiliary model completion that\n * drafts the commit message from the staged diff. Requires the\n * provider+model route to be configured on this row; without it the answer\n * is the honest not-configured failure.\n * @param request - the session whose staged diff to frame.\n * @returns the drafted message, or the failure the panel renders.\n */"
          },
          {
            "kind": "method",
            "name": "checkpoints",
            "signature": "@Remote('checkpoints') async checkpoints(request: GitRemoteCheckpointListRequest): Promise<GitRemoteResult<GitRemoteCheckpointListView>>",
            "summary": "`gitRemote.checkpoints`: the session's checkpoint series, newest first.",
            "jsDoc": "/**\n * `gitRemote.checkpoints`: the session's checkpoint series, newest first.\n * @param request - the session whose checkpoint series to read.\n * @returns the checkpoint list view, or the failure the panel renders.\n */"
          },
          {
            "kind": "method",
            "name": "restoreCheckpoint",
            "signature": "@Remote('restoreCheckpoint') async restoreCheckpoint( request: GitRemoteCheckpointRestoreRequest, ): Promise<GitRemoteResult<{ restored: readonly string[] }>>",
            "summary": "`gitRemote.restoreCheckpoint`: return work-tree files to one checkpoint.",
            "jsDoc": "/**\n * `gitRemote.restoreCheckpoint`: return work-tree files to one checkpoint.\n * @param request - the session, the checkpoint ordinal, and optional paths.\n * @returns the restored echo, or the failure the panel renders.\n */"
          }
        ],
        "types": [
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "GitRemoteBranch",
            "declaration": "export interface GitRemoteBranch {\n    readonly name: string;\n    readonly current: boolean;\n    readonly shortHash: string;\n    readonly upstream?: string;\n}"
          },
          {
            "name": "GitRemoteBranchListView",
            "declaration": "export interface GitRemoteBranchListView {\n    readonly branches: readonly GitRemoteBranch[];\n}"
          },
          {
            "name": "GitRemoteCheckpoint",
            "declaration": "export interface GitRemoteCheckpoint {\n    readonly series: string;\n    readonly index: number;\n    readonly hash: string;\n    readonly shortHash: string;\n    readonly label: string;\n    readonly date: string;\n}"
          },
          {
            "name": "GitRemoteCheckpointListRequest",
            "declaration": "export interface GitRemoteCheckpointListRequest {\n    readonly sessionId: SessionId;\n}"
          },
          {
            "name": "GitRemoteCheckpointListView",
            "declaration": "export interface GitRemoteCheckpointListView {\n    readonly checkpoints: readonly GitRemoteCheckpoint[];\n}"
          },
          {
            "name": "GitRemoteCheckpointRestoreRequest",
            "declaration": "export interface GitRemoteCheckpointRestoreRequest {\n    readonly sessionId: SessionId;\n    readonly index: number;\n    readonly paths?: readonly string[];\n}"
          },
          {
            "name": "GitRemoteCommitRequest",
            "declaration": "export interface GitRemoteCommitRequest {\n    readonly sessionId: SessionId;\n    readonly message: string;\n}"
          },
          {
            "name": "GitRemoteCommitView",
            "declaration": "export interface GitRemoteCommitView {\n    readonly hash: string;\n    readonly shortHash: string;\n    readonly subject: string;\n}"
          },
          {
            "name": "GitRemoteDiffRequest",
            "declaration": "export interface GitRemoteDiffRequest {\n    readonly sessionId: SessionId;\n    readonly staged?: boolean;\n    readonly path?: string;\n}"
          },
          {
            "name": "GitRemoteDiffView",
            "declaration": "export interface GitRemoteDiffView {\n    readonly staged: boolean;\n    readonly patch: string;\n    readonly truncated: boolean;\n    readonly path?: string;\n}"
          },
          {
            "name": "GitRemoteGeneratedMessageView",
            "declaration": "export interface GitRemoteGeneratedMessageView {\n    readonly message: string;\n}"
          },
          {
            "name": "GitRemoteLogEntry",
            "declaration": "export interface GitRemoteLogEntry {\n    readonly hash: string;\n    readonly shortHash: string;\n    readonly author: string;\n    readonly date: string;\n    readonly subject: string;\n}"
          },
          {
            "name": "GitRemoteLogRequest",
            "declaration": "export interface GitRemoteLogRequest {\n    readonly sessionId: SessionId;\n    readonly maxCount?: number;\n    readonly ref?: string;\n    readonly path?: string;\n}"
          },
          {
            "name": "GitRemoteLogView",
            "declaration": "export interface GitRemoteLogView {\n    readonly entries: readonly GitRemoteLogEntry[];\n}"
          },
          {
            "name": "GitRemotePushRequest",
            "declaration": "export interface GitRemotePushRequest {\n    readonly sessionId: SessionId;\n    readonly remote?: string;\n    readonly branch?: string;\n    readonly setUpstream?: boolean;\n}"
          },
          {
            "name": "GitRemotePushView",
            "declaration": "export interface GitRemotePushView {\n    readonly remote: string;\n    readonly branch: string;\n    readonly setUpstream: boolean;\n}"
          },
          {
            "name": "GitRemoteResult",
            "declaration": "export type GitRemoteResult<T> = { readonly ok: true; readonly value: T; } | { readonly ok: false; readonly error: string; readonly denied?: boolean; };"
          },
          {
            "name": "GitRemoteSessionRequest",
            "declaration": "export interface GitRemoteSessionRequest {\n    readonly sessionId: SessionId;\n}"
          },
          {
            "name": "GitRemoteStageRequest",
            "declaration": "export interface GitRemoteStageRequest {\n    readonly sessionId: SessionId;\n    readonly paths?: readonly string[];\n    readonly all?: boolean;\n}"
          },
          {
            "name": "GitRemoteStageView",
            "declaration": "export interface GitRemoteStageView {\n    readonly stagedPaths: readonly string[];\n}"
          },
          {
            "name": "GitRemoteStatusEntry",
            "declaration": "export interface GitRemoteStatusEntry {\n    readonly code: string;\n    readonly path: string;\n    readonly staged: boolean;\n    readonly unstaged: boolean;\n    readonly untracked: boolean;\n    readonly originPath?: string;\n}"
          },
          {
            "name": "GitRemoteStatusView",
            "declaration": "export interface GitRemoteStatusView {\n    readonly root: string;\n    readonly ahead: number;\n    readonly behind: number;\n    readonly initial: boolean;\n    readonly detached: boolean;\n    readonly branch?: string;\n    readonly upstream?: string;\n    readonly entries: readonly GitRemoteStatusEntry[];\n}"
          },
          {
            "name": "SessionId",
            "declaration": "export type SessionId = Branded<'SessionId'>;"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
