/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _dsh_custom_dsh_automations_remote_automationsRemote_create_parameter_0$schema = z.object({
  'title': z.string().readonly(),
  'workspacePath': z.string().readonly(),
  'prompt': z.string().readonly(),
  'cron': z.string().readonly(),
})
const _dsh_custom_dsh_automations_remote_automationsRemote_create_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.string().readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'id': z.string().readonly(),
  'title': z.string().readonly(),
  'workspacePath': z.string().readonly(),
  'prompt': z.string().readonly(),
  'cron': z.string().readonly(),
  'enabled': z.boolean().readonly(),
  'nextRunAt': z.union([z.literal(null), z.string()]).readonly(),
  'lastRunAt': z.union([z.literal(null), z.string()]).readonly(),
  'lastOutcome': z.union([z.literal("error"), z.literal("ok")]).readonly().optional(),
  'lastError': z.string().readonly().optional(),
}).readonly(),
})])
const _dsh_custom_dsh_automations_remote_automationsRemote_deleteAutomation_parameter_0$schema = z.object({
  'id': z.string().readonly(),
})
const _dsh_custom_dsh_automations_remote_automationsRemote_deleteAutomation_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.string().readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.literal(null).readonly(),
})])
const _dsh_custom_dsh_automations_remote_automationsRemote_list_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.string().readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'automations': z.array(z.object({
  'id': z.string().readonly(),
  'title': z.string().readonly(),
  'workspacePath': z.string().readonly(),
  'prompt': z.string().readonly(),
  'cron': z.string().readonly(),
  'enabled': z.boolean().readonly(),
  'nextRunAt': z.union([z.literal(null), z.string()]).readonly(),
  'lastRunAt': z.union([z.literal(null), z.string()]).readonly(),
  'lastOutcome': z.union([z.literal("error"), z.literal("ok")]).readonly().optional(),
  'lastError': z.string().readonly().optional(),
})).readonly(),
}).readonly(),
})])
const _dsh_custom_dsh_automations_remote_automationsRemote_runNow_parameter_0$schema = z.object({
  'id': z.string().readonly(),
})
const _dsh_custom_dsh_automations_remote_automationsRemote_runNow_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.string().readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.literal(null).readonly(),
})])
const _dsh_custom_dsh_automations_remote_automationsRemote_update_parameter_0$schema = z.object({
  'id': z.string().readonly(),
  'title': z.string().readonly().optional(),
  'prompt': z.string().readonly().optional(),
  'cron': z.string().readonly().optional(),
  'enabled': z.boolean().readonly().optional(),
})
const _dsh_custom_dsh_automations_remote_automationsRemote_update_result$schema = z.union([z.object({
  'ok': z.literal(false).readonly(),
  'error': z.string().readonly(),
}), z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'id': z.string().readonly(),
  'title': z.string().readonly(),
  'workspacePath': z.string().readonly(),
  'prompt': z.string().readonly(),
  'cron': z.string().readonly(),
  'enabled': z.boolean().readonly(),
  'nextRunAt': z.union([z.literal(null), z.string()]).readonly(),
  'lastRunAt': z.union([z.literal(null), z.string()]).readonly(),
  'lastOutcome': z.union([z.literal("error"), z.literal("ok")]).readonly().optional(),
  'lastError': z.string().readonly().optional(),
}).readonly(),
})])

export const TYPERT = {
  package: '@dsh-custom/dsh-automations-remote',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@dsh-custom/dsh-automations-remote#automationsRemote/create',
      service: 'automationsRemote',
      namespace: 'automationsRemote',
      method: 'create',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-custom/dsh-automations-remote/types#AutomationCreateRequest',
            schema: _dsh_custom_dsh_automations_remote_automationsRemote_create_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-custom/dsh-automations-remote/types#AutomationsRemoteResult',
        schema: _dsh_custom_dsh_automations_remote_automationsRemote_create_result$schema,
      },
      sourceLocation: {"file":"packages/schedule/automations-remote/src/index.ts","line":84,"column":9},
    },
    {
      id: '@dsh-custom/dsh-automations-remote#automationsRemote/deleteAutomation',
      service: 'automationsRemote',
      namespace: 'automationsRemote',
      method: 'deleteAutomation',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-custom/dsh-automations-remote/types#AutomationIdRequest',
            schema: _dsh_custom_dsh_automations_remote_automationsRemote_deleteAutomation_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-custom/dsh-automations-remote/types#AutomationsRemoteResult',
        schema: _dsh_custom_dsh_automations_remote_automationsRemote_deleteAutomation_result$schema,
      },
      sourceLocation: {"file":"packages/schedule/automations-remote/src/index.ts","line":107,"column":9},
    },
    {
      id: '@dsh-custom/dsh-automations-remote#automationsRemote/list',
      service: 'automationsRemote',
      namespace: 'automationsRemote',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-custom/dsh-automations-remote/types#AutomationsRemoteResult',
        schema: _dsh_custom_dsh_automations_remote_automationsRemote_list_result$schema,
      },
      sourceLocation: {"file":"packages/schedule/automations-remote/src/index.ts","line":71,"column":9},
    },
    {
      id: '@dsh-custom/dsh-automations-remote#automationsRemote/runNow',
      service: 'automationsRemote',
      namespace: 'automationsRemote',
      method: 'runNow',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-custom/dsh-automations-remote/types#AutomationIdRequest',
            schema: _dsh_custom_dsh_automations_remote_automationsRemote_runNow_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-custom/dsh-automations-remote/types#AutomationsRemoteResult',
        schema: _dsh_custom_dsh_automations_remote_automationsRemote_runNow_result$schema,
      },
      sourceLocation: {"file":"packages/schedule/automations-remote/src/index.ts","line":120,"column":9},
    },
    {
      id: '@dsh-custom/dsh-automations-remote#automationsRemote/update',
      service: 'automationsRemote',
      namespace: 'automationsRemote',
      method: 'update',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-custom/dsh-automations-remote/types#AutomationUpdateRequest',
            schema: _dsh_custom_dsh_automations_remote_automationsRemote_update_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-custom/dsh-automations-remote/types#AutomationsRemoteResult',
        schema: _dsh_custom_dsh_automations_remote_automationsRemote_update_result$schema,
      },
      sourceLocation: {"file":"packages/schedule/automations-remote/src/index.ts","line":94,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "tags": [],
        "key": "automationsRemote",
        "exportName": "AutomationsRemoteService",
        "members": [
          {
            "kind": "method",
            "name": "list",
            "signature": "@Remote('list') async list(): Promise<AutomationsRemoteResult<AutomationListView>>",
            "summary": "`automationsRemote.list`: every automation, in creation order.",
            "jsDoc": "/**\n * `automationsRemote.list`: every automation, in creation order.\n * @returns the list view, or the failure the panel renders.\n */"
          },
          {
            "kind": "method",
            "name": "create",
            "signature": "@Remote('create') async create(request: AutomationCreateRequest): Promise<AutomationsRemoteResult<AutomationView>>",
            "summary": "`automationsRemote.create`: one automation; the first run time is computed.",
            "jsDoc": "/**\n * `automationsRemote.create`: one automation; the first run time is computed.\n * @param request - title, absolute workspace, prompt, cron expression.\n * @returns the created view, or the failure the panel renders.\n */"
          },
          {
            "kind": "method",
            "name": "update",
            "signature": "@Remote('update') async update(request: AutomationUpdateRequest): Promise<AutomationsRemoteResult<AutomationView>>",
            "summary": "`automationsRemote.update`: editable fields; a cron change recomputes the schedule.",
            "jsDoc": "/**\n * `automationsRemote.update`: editable fields; a cron change recomputes the schedule.\n * @param request - the id and the fields to replace.\n * @returns the updated view, or the failure the panel renders.\n */"
          },
          {
            "kind": "method",
            "name": "deleteAutomation",
            "signature": "@Remote('deleteAutomation') async deleteAutomation(request: AutomationIdRequest): Promise<AutomationsRemoteResult<null>>",
            "summary": "`automationsRemote.deleteAutomation`: delete one automation.",
            "jsDoc": "/**\n * `automationsRemote.deleteAutomation`: delete one automation.\n * @param request - the id to remove.\n * @returns an empty value, or the failure the panel renders.\n */"
          },
          {
            "kind": "method",
            "name": "runNow",
            "signature": "@Remote('runNow') async runNow(request: AutomationIdRequest): Promise<AutomationsRemoteResult<null>>",
            "summary": "`automationsRemote.runNow`: fire one automation immediately, outside its schedule.",
            "jsDoc": "/**\n * `automationsRemote.runNow`: fire one automation immediately, outside its schedule.\n * @param request - the id to fire.\n * @returns an empty value, or the failure the panel renders.\n */"
          }
        ],
        "types": [
          {
            "name": "AutomationCreateRequest",
            "declaration": "export interface AutomationCreateRequest {\n    readonly title: string;\n    readonly workspacePath: string;\n    readonly prompt: string;\n    readonly cron: string;\n}"
          },
          {
            "name": "AutomationIdRequest",
            "declaration": "export interface AutomationIdRequest {\n    readonly id: string;\n}"
          },
          {
            "name": "AutomationListView",
            "declaration": "export interface AutomationListView {\n    readonly automations: readonly AutomationView[];\n}"
          },
          {
            "name": "AutomationsRemoteResult",
            "declaration": "export type AutomationsRemoteResult<T> = { readonly ok: true; readonly value: T; } | { readonly ok: false; readonly error: string; };"
          },
          {
            "name": "AutomationUpdateRequest",
            "declaration": "export interface AutomationUpdateRequest {\n    readonly id: string;\n    readonly title?: string;\n    readonly prompt?: string;\n    readonly cron?: string;\n    readonly enabled?: boolean;\n}"
          },
          {
            "name": "AutomationView",
            "declaration": "export interface AutomationView {\n    readonly id: string;\n    readonly title: string;\n    readonly workspacePath: string;\n    readonly prompt: string;\n    readonly cron: string;\n    readonly enabled: boolean;\n    readonly nextRunAt: string | null;\n    readonly lastRunAt: string | null;\n    readonly lastOutcome?: 'ok' | 'error';\n    readonly lastError?: string;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
