/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { AutomationCreateRequest, AutomationIdRequest, AutomationListView, AutomationsRemoteResult, AutomationUpdateRequest, AutomationView } from '@dsh-custom/dsh-automations-remote/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6175746f6d6174696f6e7352656d6f7465 {
    create: (request: AutomationCreateRequest) => Promise<RemoteResult<AutomationsRemoteResult<AutomationView>>>
    deleteAutomation: (request: AutomationIdRequest) => Promise<RemoteResult<AutomationsRemoteResult<null>>>
    list: () => Promise<RemoteResult<AutomationsRemoteResult<AutomationListView>>>
    runNow: (request: AutomationIdRequest) => Promise<RemoteResult<AutomationsRemoteResult<null>>>
    update: (request: AutomationUpdateRequest) => Promise<RemoteResult<AutomationsRemoteResult<AutomationView>>>
  }
  interface TypertRemoteMap {
    'automationsRemote/create': (request: AutomationCreateRequest) => Promise<RemoteResult<AutomationsRemoteResult<AutomationView>>>
    'automationsRemote/deleteAutomation': (request: AutomationIdRequest) => Promise<RemoteResult<AutomationsRemoteResult<null>>>
    'automationsRemote/list': () => Promise<RemoteResult<AutomationsRemoteResult<AutomationListView>>>
    'automationsRemote/runNow': (request: AutomationIdRequest) => Promise<RemoteResult<AutomationsRemoteResult<null>>>
    'automationsRemote/update': (request: AutomationUpdateRequest) => Promise<RemoteResult<AutomationsRemoteResult<AutomationView>>>
  }
  interface TypertRemoteNamespaceMap {
    'automationsRemote': TypertRemoteNamespace$6175746f6d6174696f6e7352656d6f7465
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
